### ISSUE TITLE
Wrong Answer  Question 249

### ISSUE THREAD

**Issue by NALAWALAMURTUZA** [Ditectrev/Microsoft-Azure-AZ-400-Designing-and-Implementing-Microsoft-DevOps-Solutions-Practice-Tests-Exams-QA#3]
You have an Azure Pipelines application CI/CD pipeline named Pipeline1. You need to add OWASP ZAP testing to Pipeline1. Which four actions should you add to Pipeline1 in sequence?
Question 249

- [ ]  Box 1: Start a container. Box 2: Run the baseline. Box 3: Run an active scan. Box 4: Report the results.
- [x]  Box 1: Pull OWASP ZAP Weekly. Box 2: Start a container. Box 3: Run the baseline. Box 4: Report the results.
- [ ]  Box 1: Spider the site. Box 2: Run the baseline. Box 3: Run an active scan. Box 4: Report the results.
- [ ]  Box 1: Spider the site. Box 2: Run the baseline. Box 3: Pull OWASP ZAP Weekly. Box 4: Report the results.

[⬆ Back to Top](https://github.com/Ditectrev/Microsoft-Azure-AZ-400-Designing-and-Implementing-Microsoft-DevOps-Solutions-Practice-Tests-Exams-QA#table-of-contents)

correct answer is

Box 1: Start a container
Box 2:Run the baseline.
Box 3:Spider the site.
Box 4:Report the results.

**Comment by danieldanielecki** [comment]
@NALAWALAMURTUZA thank you for the contribution, but there's a very good discussion on that question on https://www.examtopics.com/discussions/microsoft/view/128932-exam-az-400-topic-4-question-70-discussion/ regarding this question. Current answer is correct.
